export const questionList = [
    {question:"What was the house number and street name you lived in as a child?",
      id:1},
    {question:"What were the last four digits of your childhood telephone number?",
      id:2},
    {question:"What primary school did you attend?",
      id:3},
    {question:"In what town or city was your first full time job?",
      id:4},
    {question:"In what town or city did you meet your spouse/partner?",
      id:5},
    {question:"What is the middle name of your oldest child?",
      id:6},
    {question:"What are the last five digits of your driver's licence number?",
      id:7},
    {question:"What is your grandmother's (on your mother's side) maiden name?",
      id:8},
    {question:"What is your spouse or partner's mother's maiden name?",
      id:9},
    {question:"What time of the day were you born? (hh:mm)",
      id:10},
    {question:"What time of the day was your first child born? (hh:mm)",
      id:11},  
]